  `ad_id` int(11) NOT NULL AUTO_INCREMENT,
  `ad_as_id` int(11) DEFAULT NULL,
  `ad_language` int(11) DEFAULT NULL,
  `ad_metadata_keywords` text DEFAULT NULL,
  `ad_metadata_description` text DEFAULT NULL,
  `ad_window_title` text DEFAULT NULL,



  `AssetID` int(11) NOT NULL DEFAULT 0,
  `as_name` varchar(255) DEFAULT NULL,
  `as_subtitle` varchar(255) DEFAULT NULL,
  `as_last_modified` datetime DEFAULT NULL,
  `as_archive` tinyint(1) DEFAULT 0,
  `as_serialized` longtext DEFAULT NULL,
  `as_type` varchar(255) DEFAULT NULL,
  `as_appear_in_menus` tinyint(1) DEFAULT 1,
  `as_layout_serialized` longtext DEFAULT NULL,
  `as_dev_asset` tinyint(1) DEFAULT 0,
  `as_promotion_date` datetime DEFAULT NULL,
  `as_reversion_date` datetime DEFAULT NULL,
  `as_sort_order` int(11) DEFAULT NULL,
  `as_parent_as_id` int(11) DEFAULT NULL,
  `as_owner_au_id` int(11) DEFAULT 1,
  `as_system` tinyint(1) DEFAULT 0,
  `as_hidden` tinyint(1) DEFAULT 0,
  `as_header_name` varchar(255) DEFAULT NULL,
  `as_menu_name` varchar(255) DEFAULT NULL,
  `as_can_use_default` tinyint(1) DEFAULT NULL,
  `as_can_admin_default` tinyint(1) DEFAULT NULL,
  `as_child_can_use_default` tinyint(1) DEFAULT NULL,
  `as_child_can_admin_default` tinyint(1) DEFAULT NULL,
  `as_deleted` tinyint(1) DEFAULT 0,
  `as_search_keywords` longtext DEFAULT NULL,
  `as_search_description` longtext DEFAULT NULL,
  `as_search_content` longtext DEFAULT NULL,
  `as_not_allowed_search` tinyint(1) NOT NULL DEFAULT 0,

  `aug_ug_id` int(11) NOT NULL DEFAULT 0,
  `AssetLink` int(11) NOT NULL DEFAULT 0,
`CanUse` tinyint(1) DEFAULT 0,
  `CanAdminister` tinyint(1) DEFAULT 0,
  `ChildCanUse` tinyint(1) NOT NULL DEFAULT 0,
  `ChildCanAdminister` tinyint(1) NOT NULL DEFAULT 0,

  `at_id` int(11) NOT NULL DEFAULT 0,
  `at_display` varchar(50) DEFAULT NULL,
  `at_name` varchar(50) DEFAULT NULL,
  `at_limit` int(11) DEFAULT NULL,
  `at_allow_search` tinyint(1) DEFAULT NULL,

    `UserLink` int(11) NOT NULL DEFAULT 0,
  `AssetLink` int(11) NOT NULL DEFAULT 0,
  `CanUse` tinyint(1) DEFAULT 0,
  `CanAdminister` tinyint(1) DEFAULT 0,
  `ApplyToChildren` tinyint(1) DEFAULT 0,

  `bo_id` int(11) NOT NULL AUTO_INCREMENT,
  `bo_as_id` int(11) DEFAULT NULL,
  `bo_details` longtext DEFAULT NULL,
  `bo_tr_id` int(11) DEFAULT NULL,
  `bo_date` datetime DEFAULT NULL,
  `bo_paid` tinyint(1) DEFAULT NULL,
  `bo_email_address` varchar(255) DEFAULT NULL,

    `cit_id` int(11) NOT NULL DEFAULT 0,
  `cit_as_id` int(11) DEFAULT NULL,
  `cit_title` varchar(255) DEFAULT NULL,
  `cit_content` longtext DEFAULT NULL,
  `cit_sort_order` int(11) DEFAULT NULL,

  `cfg_id` int(11) NOT NULL DEFAULT 0,
  `cfg_website_name` varchar(127) DEFAULT NULL,
  `cfg_email_address` varchar(255) DEFAULT NULL,
  `cfg_bcc_address` varchar(255) DEFAULT NULL,
  `cfg_keywords` text DEFAULT NULL,
  `cfg_description` text DEFAULT NULL,
  `cfg_contact_details` text DEFAULT NULL,
  `cfg_options` text DEFAULT NULL,
  `cfg_last_or_id` int(11) DEFAULT NULL,
  `cfg_last_us_id` int(11) DEFAULT NULL,
  `cfg_version` int(11) DEFAULT NULL,
  `cfg_version_update_date` datetime DEFAULT NULL,
  `cfg_secure_server` varchar(255) DEFAULT NULL,
  `cfg_plaintext_server` varchar(255) DEFAULT NULL,
  `cfg_folder_name` varchar(50) NOT NULL DEFAULT '',
  `cf_is_service` tinyint(1) DEFAULT NULL,


  `cn_id` int(11) NOT NULL DEFAULT 0,
  `cn_name` varchar(127) DEFAULT NULL,
  `cn_currency` varchar(127) DEFAULT NULL,
  `cn_two_code` char(2) DEFAULT NULL,
  `cn_three_code` char(3) DEFAULT NULL,
  `cn_currency_code` varchar(5) DEFAULT NULL,
  `cn_currency_symbol` varchar(10) DEFAULT NULL,
  `cn_disabled` tinyint(1) DEFAULT NULL,
  `cn_currency_disabled` tinyint(1) DEFAULT NULL,
  `cn_disable_access` tinyint(1) DEFAULT NULL,
  `cn_disable_access_code` varchar(128) DEFAULT NULL,
  `cn_note` longtext DEFAULT NULL,
  `cn_display_as_id` int(11) DEFAULT NULL,
  `cn_restrict_shipping` int(1) DEFAULT NULL,
  `cn_tax_x100` int(11) DEFAULT NULL,
  `cn_warning` longtext DEFAULT NULL,
  `cn_usps_ident` varchar(40) DEFAULT NULL,
  `cn_hold_status` enum('No','Maybe','Yes') DEFAULT NULL,
  `cn_max_order_total` int(11) NOT NULL DEFAULT 99999,
  `cn_warning_email` text DEFAULT NULL,
  `cn_generic_limit` int(11) NOT NULL DEFAULT 99999,
  `cn_min_reorder_interval` int(11) NOT NULL DEFAULT 0,
  `cn_redirect_url` varchar(255) DEFAULT NULL,
  `cn_shipping_tracking` enum('None','Optional','Mandatory','By User') NOT NULL,
  `cn_sales_zones` varchar(64) DEFAULT NULL,
  `cn_max_order_boxes` int(11) DEFAULT NULL,
  `cn_precision` int(11) NOT NULL DEFAULT 2,
  `cn_box_tracking_cost_x100` int(11) DEFAULT NULL,
  `cn_box_tracking_cost_currency` char(3) DEFAULT NULL,
  `cn_shipping_label` text DEFAULT NULL,
  `cn_no_chargeback_count` int(11) NOT NULL DEFAULT 0,
  `cn_post_zone` enum('Europe','USA','RestOfWorld','Canada') DEFAULT NULL,
  `cn_ship_via_distributor` int(11) DEFAULT NULL,
  `cn_bypass_stock_control` enum('false','true') NOT NULL,
  `cn_shipping_penalty_min_total` int(11) NOT NULL DEFAULT 150,
  `cn_shop_phone_shipping_label` enum('no','yes') DEFAULT 'no',
  `cn_label_type` enum('none','original','harmonized') DEFAULT 'original',

  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `Date` date NOT NULL DEFAULT '0000-00-00',
  `Total` int(11) DEFAULT NULL,

    `das_id` int(11) NOT NULL AUTO_INCREMENT,
  `das_date` date NOT NULL DEFAULT '0000-00-00',
  `das_as_id` int(11) DEFAULT NULL,
  `das_hits` int(11) DEFAULT NULL,
  `das_user_hits` int(11) DEFAULT NULL,

    `mt_id` int(11) DEFAULT NULL,
  `mt_keywords` text DEFAULT NULL,
  `mt_description` text DEFAULT NULL,
  `mt_title` text DEFAULT NULL


    `efs_id` int(11) NOT NULL AUTO_INCREMENT,
  `efs_timestamp` datetime DEFAULT NULL,
  `efs_email_address` varchar(255) DEFAULT NULL,
  `efs_text` longtext DEFAULT NULL,
  `efs_as_id` int(11) DEFAULT NULL,
  `efs_name` varchar(255) DEFAULT NULL,

  `fm_id` int(11) NOT NULL DEFAULT 1,
  `fm_thr_id` int(11) NOT NULL DEFAULT 0,
  `fm_content` longtext DEFAULT NULL,
  `fm_poster_firstname` varchar(127) DEFAULT NULL,
  `fm_poster_lastname` varchar(127) DEFAULT NULL,
  `fm_poster_email` varchar(255) DEFAULT NULL,
  `fm_poster_us_id` int(11) DEFAULT NULL,
  `fm_replying_fm_id` int(11) DEFAULT NULL,
  `fm_timestamp` datetime DEFAULT NULL,

  `thr_id` int(11) NOT NULL DEFAULT 0,
  `thr_subject` longtext DEFAULT NULL,
  `thr_views` int(11) DEFAULT 0,
  `thr_locked` tinyint(1) NOT NULL DEFAULT 0,
  `thr_created` datetime DEFAULT NULL,
  `thr_as_id` int(11) DEFAULT NULL,
  `thr_last_thr_id` int(11) DEFAULT NULL,


  `imu_id` int(11) NOT NULL DEFAULT 0,
  `imu_user_data` longtext DEFAULT NULL,
  `imu_user_code` varchar(50) DEFAULT NULL,


  `lg_id` int(11) NOT NULL DEFAULT 0,
  `lg_name` varchar(255) DEFAULT NULL,
  `lg_charset` varchar(255) DEFAULT NULL,
  `lg_site_url` char(99) DEFAULT NULL,
  `lg_watermark` varchar(100) DEFAULT NULL


  `los_us_id` int(11) NOT NULL DEFAULT 0,
  `los_timestamp` datetime NOT NULL DEFAULT '0000-00-00 00:00:00'


  `lotw_id` int(11) NOT NULL AUTO_INCREMENT,
  `lotw_or_id` int(11) DEFAULT NULL,
  `lotw_pr_id` int(11) DEFAULT NULL,
  `lotw_pro_id` int(11) DEFAULT NULL,
  `lotw_draw_date` datetime DEFAULT NULL,
  `lotw_content` longtext DEFAULT NULL,
  `lotw_upcoming` tinyint(1) DEFAULT NULL,
  `lotw_this_week` tinyint(1) DEFAULT NULL,



  `rel_id` int(11) NOT NULL DEFAULT 0,
  `rel_file` varchar(255) DEFAULT NULL,
  `rel_date` date DEFAULT NULL,
  `rel_title` varchar(255) DEFAULT NULL,
  `rel_description` longtext DEFAULT NULL,
  `rel_approved` tinyint(1) DEFAULT NULL,
  `rel_as_id` int(11) DEFAULT NULL,

  `mo_us_id` int(11) NOT NULL DEFAULT 0,
  `mo_tr_id` int(11) NOT NULL DEFAULT 0,
  `mo_as_id` int(11) NOT NULL DEFAULT 0,
  `mo_sub_id` int(11) NOT NULL DEFAULT 0,
  `mo_token` varchar(255) NOT NULL DEFAULT '',
  `mo_approved` tinyint(1) NOT NULL DEFAULT 0

  `msp_id` int(11) NOT NULL DEFAULT 0,
  `msp_sub_id` int(11) NOT NULL DEFAULT 0,
  `msp_cn_id` int(11) NOT NULL DEFAULT 0,
  `msp_price` double NOT NULL DEFAULT 0,

  `ms_id` int(11) NOT NULL DEFAULT 0,
  `ms_name` varchar(255) DEFAULT NULL,
  `ms_length` int(11) DEFAULT NULL,
  `ms_default_price` double DEFAULT NULL,
  `ms_default_cn_id` int(11) DEFAULT NULL,
  `ms_description` longtext DEFAULT NULL,
  `ms_as_id` int(11) DEFAULT NULL,



  `mv_us_id` int(11) NOT NULL DEFAULT 0,
  `mv_created` datetime DEFAULT NULL,
  `mv_allowed` tinyint(4) DEFAULT NULL,

// na_
  `na_id` int(11) NOT NULL DEFAULT 0,
  `na_sent` datetime DEFAULT NULL,
  `na_us_id` int(11) DEFAULT NULL,
  `na_user_firstname` varchar(127) DEFAULT NULL,
  `na_user_lastname` varchar(127) DEFAULT NULL,
  `` varchar(255) DEFAULT NULL,
  `na_content` longtext DEFAULT NULL,
  `na_current` tinyint(1) DEFAULT NULL,
  `na_subject` varchar(255) DEFAULT NULL,
  `na_as_id` int(11) DEFAULT NULL,
  `na_user_groups` text DEFAULT NULL,


  `ntp_id` int(11) NOT NULL DEFAULT 0,
  `ntp_name` varchar(255) DEFAULT NULL,
  `ntp_displayname` varchar(255) DEFAULT NULL,
  `ntp_as_id` int(11) DEFAULT NULL,

    `BlLiID` int(11) NOT NULL DEFAULT 0,
  `BlLiBillingName` varchar(127) DEFAULT NULL,
  `BlLiBillingAddress` varchar(255) DEFAULT NULL,
  `BlLiShippingName` varchar(127) DEFAULT NULL,
  `BlLiShippingAddress` varchar(255) DEFAULT NULL,
  `BlLiSortOrder` int(11) DEFAULT NULL,
  `BlLiEmail` varchar(255) DEFAULT NULL,
  `BlLiNotes` longtext DEFAULT NULL,
  `BlLiIPAddress` varchar(15) DEFAULT NULL,
  `BlLiBrowserIdent` text DEFAULT NULL,
  `BlLiFingerprint` text DEFAULT NULL,

  `ca_id` int(11) NOT NULL DEFAULT 0,
  `ca_name` varchar(255) DEFAULT NULL,
  `ca_parent_ca_id` int(11) DEFAULT NULL,
  `ca_as_id` int(11) DEFAULT NULL,
  `ca_description_html` longtext DEFAULT NULL,
  `ca_image` varchar(255) DEFAULT NULL,
  `ca_sort_order` int(11) DEFAULT NULL,
  `ca_attr_setting` longtext DEFAULT NULL,
  `ca_option_setting` longtext DEFAULT NULL,
  `ca_menu_set` longtext DEFAULT NULL,
  `ca_password` varchar(255) DEFAULT NULL,
  `ca_window_title` varchar(255) DEFAULT NULL,
  `ca_appears_in_menu` tinyint(1) DEFAULT NULL,
  `ca_metadata_keywords` text DEFAULT NULL,
  `ca_metadata_description` text DEFAULT NULL,
  `ca_origin_cn_id` int(11) DEFAULT NULL,
  `ca_nav_id` int(11) NOT NULL DEFAULT 1,
  `ca_dig_id` int(11) DEFAULT NULL,
  `ca_banner` varchar(255) DEFAULT NULL,

  `cad_id` int(11) NOT NULL AUTO_INCREMENT,
  `cad_language` int(11) DEFAULT NULL,
  `cad_ca_id` int(11) DEFAULT NULL,
  `cad_name` text DEFAULT NULL,
  `cad_window_title` text DEFAULT NULL,
  `cad_description` text DEFAULT NULL,
  `cad_metadata_keywords` text DEFAULT NULL,
  `cad_metadata_description` text DEFAULT NULL,

  `cpr_id` int(11) NOT NULL AUTO_INCREMENT,
  `cpr_pr_id` int(11) DEFAULT NULL,
  `cpr_qty` int(11) DEFAULT NULL,
  `cpr_as_id` int(11) DEFAULT NULL,
  `cpr_element_pr_id` int(11) DEFAULT NULL,


    `dic_id` int(11) NOT NULL DEFAULT 0,
  `dic_name` varchar(255) DEFAULT NULL,
  `DiCoAssetLink` int(11) DEFAULT NULL,
  `DiCoRates` longtext DEFAULT NULL,
  `DiCoMessage` longtext DEFAULT NULL,


    `dig_id` int(11) NOT NULL DEFAULT 0,
  `dig_name` varchar(255) DEFAULT NULL,
  `dig_deleted` tinyint(1) DEFAULT NULL,
  `dig_as_id` int(11) DEFAULT NULL,
  `dig_sort_order` int(11) DEFAULT NULL,

// or_sh_id
  `ors_id` int(11) NOT NULL DEFAULT 0,
  `ors_date` date DEFAULT NULL,
  `ors_invoice_number` varchar(63) DEFAULT NULL,
  `ors_notes` longtext DEFAULT NULL,
  `ors_paid` date DEFAULT NULL,
  `ors_total` double DEFAULT NULL,
  `ors_invoice_date` date DEFAULT NULL,
  `ors_import` double DEFAULT NULL,
  `ors_ve_id` int(1) DEFAULT 1,
  `ors_customs_reference` text DEFAULT NULL,

// or_sh_it_id
  `orsi_id` int(11) NOT NULL AUTO_INCREMENT,
  `orsi_ors_id` int(11) DEFAULT NULL,
  `orsi_bs_code` longtext DEFAULT NULL,
  `orsi_stock_code` varchar(127) DEFAULT NULL,
  `orsi_pr_name` varchar(255) DEFAULT NULL,
  `orsi_qty` int(11) DEFAULT NULL,
  `orsi_price` double DEFAULT NULL,
  `orsi_discount` double DEFAULT NULL,
  `orsi_shipping` double DEFAULT 0,
  `orsi_total` double DEFAULT NULL,
  `orsi_date_changed` datetime DEFAULT NULL,
  `orsi_or_id` int(11) NOT NULL DEFAULT 0,
  `orsi_batched` date DEFAULT NULL,
  `orsi_date_shipped` datetime DEFAULT NULL,
  `orsi_tracking_number` varchar(64) DEFAULT NULL,
  `orsi_no_stock` datetime DEFAULT NULL,
  `orsi_wont_ship` datetime DEFAULT NULL,
  `orsi_box_number` int(11) DEFAULT NULL,
  `orsi_received` date DEFAULT NULL,
  `orsi_cost_price` double NOT NULL,
  `orsi_sheet_pos` int(11) DEFAULT NULL,
  `orsi_usd_rate` float NOT NULL DEFAULT 1,
  `orsi_sil_id` int(11) DEFAULT NULL,
  `orsi_pr_id` int(11) NOT NULL,

// or_it_stock_code
  `oi_stock_code` varchar(64) DEFAULT NULL,
  `oi_name` longtext DEFAULT NULL,
  `oi_or_id` int(11) DEFAULT NULL,
  `oi_qty` int(11) DEFAULT NULL,
  `oi_eos_id` int(11) DEFAULT NULL,
  `oi_ve_id` int(1) DEFAULT 1,
  `oi_box_number` int(11) DEFAULT NULL,

  `fe_id` int(11) NOT NULL DEFAULT 0,
  `fe_name` varchar(255) DEFAULT NULL,
  `fe_as_id` int(11) DEFAULT NULL,
  `fe_description` longtext DEFAULT NULL,
  `fe_image` varchar(255) DEFAULT NULL,
  `fe_sort_order` int(11) DEFAULT NULL,

  `inv_id` int(11) NOT NULL DEFAULT 0,
  `in_sender_company` varchar(255) DEFAULT NULL,
  `in_sender_address` varchar(255) DEFAULT NULL,
  `in_sender_phone` varchar(255) DEFAULT NULL,
  `in_date` date DEFAULT NULL,
  `in_paymethod` varchar(255) DEFAULT NULL,
  `in_destination` varchar(255) DEFAULT NULL,
  `in_country` varchar(255) DEFAULT NULL,
  `in_boxes` varchar(255) DEFAULT NULL,
  `in_parcels` varchar(255) DEFAULT NULL,
  `in_value` varchar(255) DEFAULT NULL,
  `in_unit_value` varchar(255) DEFAULT NULL,
  `in_units` varchar(255) DEFAULT NULL,
  `in_origin` varchar(255) DEFAULT NULL,
  `in_total_value` varchar(255) DEFAULT NULL,
  `in_document` varchar(255) DEFAULT NULL,
  `in_or_id` int(11) DEFAULT NULL,
  `in_products` longtext DEFAULT NULL,
  `in_swiss_products` longtext DEFAULT NULL,

    `orn_id` int(11) NOT NULL AUTO_INCREMENT,
  `orn_text` longtext DEFAULT NULL,
  `orn_timestamp` datetime DEFAULT NULL,
  `orn_or_id` int(11) DEFAULT NULL,
  `orn_show_packing` tinyint(1) NOT NULL DEFAULT 0,


  `orpr_or_id` int(11) NOT NULL DEFAULT 0,
  `orpr_pr_id` int(11) NOT NULL DEFAULT 0,
  `orpr_pr_name` varchar(255) NOT NULL DEFAULT '',
  `orpr_price` double DEFAULT NULL,
  `orpr_qty` int(11) DEFAULT NULL,
  `orpr_timestamp` datetime DEFAULT NULL,
  `orpr_site_folder` varchar(50) DEFAULT NULL,


  `or_id` int(11) NOT NULL AUTO_INCREMENT,
  `or_tr_id` int(11) DEFAULT NULL,
  `or_purchaser_email` varchar(127) DEFAULT NULL,
  `or_details` longtext DEFAULT NULL,
  `or_shipping_details` longtext DEFAULT NULL,
  `or_recorded` datetime DEFAULT NULL,
  `or_actioned` datetime DEFAULT NULL,
  `or_shipped` datetime DEFAULT NULL,
  `or_tracking_code` varchar(255) DEFAULT NULL,
  `or_paid` datetime DEFAULT NULL,
  `or_purchaser_firstname` varchar(127) DEFAULT NULL,
  `or_purchaser_lastname` varchar(127) DEFAULT NULL,
  `or_as_id` int(11) DEFAULT NULL,
  `or_total` varchar(50) DEFAULT NULL,
  `or_us_id` int(11) DEFAULT NULL,
  `or_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `or_user_ipaddress` varchar(50) DEFAULT NULL,
  `or_tracked_and_traced` datetime DEFAULT NULL,
  `or_track_and_trace_code` varchar(255) DEFAULT NULL,
  `or_track_link` longtext DEFAULT NULL,
  `or_error_codes` longtext DEFAULT NULL,
  `or_discount_code` varchar(255) DEFAULT NULL,
  `or_basket` longtext DEFAULT NULL,
  `or_invoiced` datetime DEFAULT NULL,
  `or_site_folder` varchar(50) DEFAULT NULL,
  `or_paid_not_shipped` date DEFAULT NULL,
  `or_charge_list` tinyint(1) DEFAULT NULL,
  `or_card_denied` datetime DEFAULT NULL,
  `or_cancelled` datetime DEFAULT NULL,
  `or_standby` datetime DEFAULT NULL,
  `or_authorisation_number` varchar(63) DEFAULT NULL,
  `or_not_new` tinyint(1) DEFAULT NULL,
  `or_shipping_values` longtext DEFAULT NULL,
  `or_reshipment` datetime DEFAULT NULL,
  `or_out_of_stock` datetime DEFAULT NULL,
  `or_profit` double DEFAULT 0,
  `or_lottery` datetime DEFAULT NULL,
  `or_follow_up_status` varchar(10) DEFAULT NULL,
  `or_archive_year` int(11) DEFAULT NULL,
  `or_country` int(11) DEFAULT NULL,
  `or_summarised` tinyint(1) NOT NULL DEFAULT 0,


  `prd_id` int(11) NOT NULL DEFAULT 0,
  `prd_pr_id` int(11) NOT NULL DEFAULT 0,
  `prd_language` int(11) NOT NULL DEFAULT 0,
  `prd_pr_name` varchar(255) DEFAULT NULL,
  `prd_short` longtext DEFAULT NULL,
  `prd_long` longtext DEFAULT NULL,
  `prd_keywords` longtext DEFAULT NULL,
  `prd_window_title` longtext DEFAULT NULL,
  `prd_metadata_description` longtext DEFAULT NULL,
  `prd_0_2368` longtext DEFAULT NULL,
  `prd_0_883F` longtext DEFAULT NULL,

  `pro_id` int(11) NOT NULL AUTO_INCREMENT,
  `pro_uuids` longtext DEFAULT NULL,
  `pro_pr_id` int(11) NOT NULL DEFAULT 0,
  `pro_stock_code` varchar(127) DEFAULT NULL,
  `pro_price` double DEFAULT NULL,
  `pro_special_price` double DEFAULT NULL,
  `pro_member_price` double DEFAULT NULL,
  `pro_rrp_price` double DEFAULT NULL,
  `pro_name` varchar(255) DEFAULT NULL,
  `pro_image` varchar(255) DEFAULT NULL,
  `pro_is_main` tinyint(1) DEFAULT 0,
  `pro_cn_three_code` char(3) DEFAULT NULL,
  `pro_supplier_price` double DEFAULT NULL,
  `pro_supplier_disount` double DEFAULT NULL,
  `pro_stock_available` int(11) DEFAULT NULL,
  `pro_stock_unavailable` int(11) NOT NULL DEFAULT 0,
  `pro_date_in_stock` datetime DEFAULT NULL,
  `pro_source_currency` char(3) NOT NULL DEFAULT 'EUR',
  `pro_wholesaler_price` double DEFAULT NULL,
  `pro_weight` int(11) DEFAULT 0,
  `pro_deleted` tinyint(1) DEFAULT NULL,
  `pro_typical_daily_sales` int(11) DEFAULT NULL,
  `pro_supplier_sku` varchar(255) DEFAULT NULL,
  `pro_net_weight` int(11) DEFAULT 0,
  `pro_country_price_override` varchar(50) DEFAULT NULL,


  `pr_id` int(11) NOT NULL DEFAULT 0,
  `pr_name` varchar(255) DEFAULT NULL,
  `pr_short` longtext DEFAULT NULL,
  `pr_long` longtext DEFAULT NULL,
  `pr_image1_thumb` varchar(255) DEFAULT NULL,
  `pr_image1_normal` varchar(255) DEFAULT NULL,
  `pr_image1_large` varchar(255) DEFAULT NULL,
  `pr_image2_normal` varchar(255) DEFAULT NULL,
  `pr_image2_large` varchar(255) DEFAULT NULL,
  `pr_image3_normal` varchar(255) DEFAULT NULL,
  `pr_image3_large` varchar(255) DEFAULT NULL,
  `pr_flash` varchar(255) DEFAULT NULL,
  `pr_ca_id` int(11) DEFAULT NULL,
  `pr_sub_ca_id` int(11) DEFAULT NULL,
  `pr_as_id` int(11) DEFAULT NULL,
  `pr_sort_order` int(11) DEFAULT NULL,
  `pr_keywords` longtext DEFAULT NULL,
  `pr_deleted` smallint(1) DEFAULT NULL,
  `pr_dig_id` int(11) DEFAULT NULL,
  `pr_featured` enum('no','featured','popular') NOT NULL,
  `pr_donation` tinyint(1) NOT NULL DEFAULT 0,
  `pr_data_collection_link` int(11) DEFAULT NULL,
  `pr_window_title` varchar(255) DEFAULT NULL,
  `pr_qoc_id` int(11) DEFAULT NULL,
  `pr_vip` tinyint(1) DEFAULT NULL,
  `pr0_883_f` longtext DEFAULT NULL,
  `pr_combo` tinyint(1) DEFAULT NULL,
  `pr_offline` tinyint(1) DEFAULT NULL,
  `pr_customer_rating` double DEFAULT NULL,
  `pr_customer_rating_count` int(11) DEFAULT NULL,
  `pr_points` tinyint(1) DEFAULT NULL,
  `pr_needs_extra_padding` tinyint(1) DEFAULT NULL,
  `pr_add_gift` tinyint(1) DEFAULT NULL,
  `pr_ve_id` tinyint(1) DEFAULT NULL,
  `pr_stock_graph` tinyint(1) DEFAULT NULL,
  `pr_stock_warning` tinyint(1) DEFAULT NULL,
  `pr_stock_lead_time` int(11) DEFAULT NULL,
  `pr_ship_to_eu` tinyint(1) DEFAULT NULL,
  `pr_ship_to_non_eu` tinyint(1) DEFAULT NULL,
  `pr_stock_order_urgency` int(11) NOT NULL DEFAULT 0,
  `pr_metadata_keywords` varchar(255) DEFAULT NULL,
  `pr_meta_description` varchar(255) DEFAULT NULL,
  `pr_stock_warning_level` int(11) DEFAULT NULL,
  `pr_us_only` enum('false','true') NOT NULL,
  `pr_shipping_d1` int(11) DEFAULT NULL,
  `pr_shipping_d2` int(11) DEFAULT NULL,
  `pr_shipping_d3` int(11) DEFAULT NULL,
  `pr_shipping_usps` enum('Priority Mail','Express Mail','Hold For Pickup','Large Flat-Rate Box','Regular/Medium Flat-Rate Boxes','Small Flat-Rate Box','Parcel Post') NOT NULL,
  `pr_shipping_method_us` enum('Free','USPS','FedEx','DHL') NOT NULL,
  `pr_shipping_method_international` enum('Free','USPS','FedEx','DHL') NOT NULL,
  `PrCigarLength` int(11) DEFAULT NULL,
  `PrCigarType` int(11) NOT NULL DEFAULT -1,
  `PrCigarThickness` double DEFAULT NULL,
  `pr_quote_shipping` tinyint(1) DEFAULT NULL,
  `pr_latest_batch` varchar(100) DEFAULT NULL,
  `pr_add_watermark` tinyint(1) DEFAULT NULL,
  `pr_cheapest_shipping_subsidy` double NOT NULL DEFAULT 0,
  `pr_outlet` tinyint(1) DEFAULT NULL,
  `pr_daily_special` enum('Off','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday') NOT NULL,
  `pr_upsell` tinyint(1) DEFAULT NULL,
  `pr_location` varchar(255) DEFAULT NULL,
  `pr_is_service` enum('false','true') NOT NULL,
  `pr_admin_text` varchar(255) DEFAULT NULL,
  `pr_service_default` enum('false','true','mandatory') NOT NULL DEFAULT 'false',
  `pr_service_exclude` int(11) DEFAULT NULL,
  `pr_restrict_special_to_gateway` int(11) DEFAULT NULL,
  `pr_restrict_product_to_gateway` int(11) DEFAULT NULL,
  `pr_sales_zone` tinyint(1) NOT NULL,
  `pr_authd_sales_zone` tinyint(1) NOT NULL,
  `pr_specials_sales_zone` int(11) NOT NULL DEFAULT 1,
  `pr_sales_tax_exempt` enum('false','true') NOT NULL,
  `pr_packing_list_colour` varchar(64) NOT NULL DEFAULT 'FFFFFF',

// qu_ca_id
  `qoc_id` int(11) NOT NULL DEFAULT 0,
  `qoc_name` varchar(255) DEFAULT NULL,
  `qoc_as_id` int(11) DEFAULT NULL,
  `qoc_description_html` longtext DEFAULT NULL,
  `qoc_image` varchar(255) DEFAULT NULL,
  `qoc_sort_order` int(11) DEFAULT NULL,


  `rfd_or_id` int(11) NOT NULL DEFAULT 0,
  `rfd_amount` double NOT NULL DEFAULT 0,
  `rfd_timestamp` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `rfd_key_qty` varchar(255) NOT NULL DEFAULT '',
  `rfd_summarized` tinyint(1) NOT NULL DEFAULT 0,
  `rfd_pending` tinyint(1) DEFAULT 0,
  `rfd_authorisation_number` varchar(255) DEFAULT NULL,

  `sic_id` int(11) NOT NULL,
  `sic_name` varchar(255) DEFAULT NULL,
  `sic_template_suffix` varchar(50) DEFAULT NULL,
  `sic_email_address` varchar(50) DEFAULT NULL,
  `sic_invline2` varchar(50) DEFAULT NULL,
  `sic_invline3` varchar(50) DEFAULT NULL,
  `sic_invline4` varchar(50) DEFAULT NULL,
  `sic_invline5` varchar(50) DEFAULT NULL,
  `sic_invline6` varchar(50) DEFAULT NULL,
  `sic_invline7` varchar(50) DEFAULT NULL,


    `siv_id` int(11) NOT NULL AUTO_INCREMENT,
  `sic_id` int(11) NOT NULL,
  `siv_to_sic_id` int(11) NOT NULL,
  `siv_created_date` date NOT NULL,
  `siv_paid_date` date DEFAULT NULL,
  `siv_external_reference` varchar(30) DEFAULT NULL,
  `siv_notes` varchar(255) DEFAULT NULL,
  `siv_1_created_date` date NOT NULL,
  `siv_1_text` varchar(30) DEFAULT NULL,
  `siv_1_hours` float DEFAULT NULL,
  `siv_1_amount` float DEFAULT NULL,
  `siv_1_tax` float DEFAULT NULL,
  `siv_2_created_date` date DEFAULT NULL,
  `siv_2_text` varchar(30) DEFAULT NULL,
  `siv_2_hours` float DEFAULT NULL,
  `siv_2_amount` float DEFAULT NULL,
  `siv_2_tax` float DEFAULT NULL,
  `siv_3_created_date` date DEFAULT NULL,
  `siv_3_text` varchar(30) DEFAULT NULL,
  `siv_3_hours` float DEFAULT NULL,
  `siv_3_amount` float DEFAULT NULL,
  `siv_3_tax` float DEFAULT NULL,
  `siv_4_created_date` date DEFAULT NULL,
  `siv_4_text` varchar(30) DEFAULT NULL,
  `siv_4_hours` float DEFAULT NULL,
  `siv_4_amount` float DEFAULT NULL,
  `siv_4_tax` float DEFAULT NULL,
  `siv_5_created_date` date DEFAULT NULL,
  `siv_5_text` varchar(30) DEFAULT NULL,
  `siv_5_hours` float DEFAULT NULL,
  `siv_5_amount` float DEFAULT NULL,
  `siv_5_tax` float DEFAULT NULL,
  `siv_6_created_date` date DEFAULT NULL,
  `siv_6_text` varchar(30) DEFAULT NULL,
  `siv_6_hours` float DEFAULT NULL,
  `siv_6_amount` float DEFAULT NULL,
  `siv_6_tax` float DEFAULT NULL,


  `shp_or_id` int(11) DEFAULT NULL,
  `shp_pr_name` varchar(255) DEFAULT NULL,
  `shp_stock_code` varchar(127) DEFAULT NULL,
  `shp_qty` int(11) DEFAULT NULL,
  `shp_date` date DEFAULT NULL,
  `shp_customs_number` varchar(63) DEFAULT NULL,
  `shp_ssc_id` int(11) DEFAULT NULL,
  `shp_days_since_ordered` int(11) DEFAULT NULL


  `ssc_id` int(11) NOT NULL DEFAULT 0,
  `ssc_amount` double DEFAULT NULL,
  `ssc_date` date DEFAULT NULL,
  `ssc_paid` date DEFAULT NULL,
  `ssc_reference` varchar(127) DEFAULT NULL,


  `sst_id` int(11) NOT NULL AUTO_INCREMENT,
  `sst_timestamp` datetime DEFAULT NULL,
  `sst_pr_id` int(11) DEFAULT NULL,
  `sst_ca_id` mediumtext DEFAULT NULL,
  `sst_country` varchar(255) DEFAULT NULL,

  `stn_email` varchar(255) DEFAULT NULL,
  `stn_stock_code` varchar(127) DEFAULT NULL,
  `stn_us_id` int(11) DEFAULT NULL,
  `stn_site_folder` varchar(50) DEFAULT NULL,
  `stn_sent_email` tinyint(1) DEFAULT 0


  `sto_stock_code` varchar(255) DEFAULT NULL,
  `sto_name` longtext DEFAULT NULL,
  `sto_or_id` int(11) DEFAULT NULL,
  `sto_qty` int(11) DEFAULT NULL,
  `sto_sos_id` int(11) DEFAULT NULL



  `sos_id` int(11) NOT NULL DEFAULT 0,
  `sos_date` date DEFAULT NULL,
  `sos_invoice_number` varchar(63) DEFAULT NULL,
  `sos_notes` longtext DEFAULT NULL,
  `sos_paid` date DEFAULT NULL,
  `sos_total` double DEFAULT NULL,
  `sos_invoice_date` date DEFAULT NULL,
  `sos_import` double DEFAULT NULL,
  `sos_supplier` smallint(6) DEFAULT NULL,


  `cit_id` int(11) NOT NULL AUTO_INCREMENT,
  `soit_sos_id` int(11) DEFAULT NULL,
  `soit_bs_code` longtext DEFAULT NULL,
  `soit_stock_code` varchar(127) DEFAULT NULL,
  `soit_pr_name` varchar(255) DEFAULT NULL,
  `soit_qty` int(11) DEFAULT NULL,
  `soit_price` double DEFAULT NULL,
  `soit_discount` double DEFAULT NULL,
  `soit_total` double DEFAULT NULL,
  `soit_date_changed` datetime DEFAULT NULL,

  `txc_id` int(11) NOT NULL DEFAULT 0,
  `txc_name` varchar(255) DEFAULT NULL,
  `txc_as_id` int(11) DEFAULT NULL,
  `txc_sort_order` int(11) DEFAULT NULL,


  `TrDGID` int(11) NOT NULL DEFAULT 0,
  `TrDGCreatedDate` date DEFAULT NULL,
  `TrDGNotes` varchar(255) DEFAULT NULL,


  `TrDGLDoID` int(11) NOT NULL DEFAULT 0,
  `TrDGLID` int(11) NOT NULL DEFAULT 0,


   `TrDoID` int(11) NOT NULL DEFAULT 0,
  `TrDoInvoice` int(11) DEFAULT NULL,
  `TrDoNodeDUA` varchar(255) DEFAULT NULL,
  `TrDoNodeBultos` varchar(255) DEFAULT NULL,
  `TrDoPesoBruto` varchar(255) DEFAULT NULL,
  `TrDoMercancia` varchar(255) DEFAULT NULL,
  `TrDoUnidades` varchar(255) DEFAULT NULL,
  `TrDoNoCuentaExistencias` varchar(255) DEFAULT NULL,
  `TrDoNombreDestinatarioenDua` varchar(255) DEFAULT NULL,
  `TrDoSolicitud` longtext DEFAULT NULL,
  `TrDoElSolicitante` varchar(255) DEFAULT NULL,
  `TrDoComosePide` varchar(255) DEFAULT NULL,
  `TrDoNota` longtext DEFAULT NULL,
  `TrDoOrderLink` int(11) DEFAULT NULL,
  `TrDoAssetLink` int(11) DEFAULT NULL,
  `TrDoLasPalmasdeGCFecha` datetime DEFAULT NULL,
  `TrDoEspacioparaSellodeEmpresa` varchar(255) DEFAULT NULL,
  `TrDoEspacioparaselloaduanas` longtext DEFAULT NULL,
  `TrDoInvoiceLink` int(11) DEFAULT NULL,


  `up_id` int(11) NOT NULL DEFAULT 0,
  `up_or_id` int(11) DEFAULT NULL,
  `up_points` double DEFAULT NULL,
  `up_expires` date DEFAULT NULL,
  `up_us_id` int(11) DEFAULT NULL,
  `up_used` int(11) DEFAULT NULL,

// ps_pr_id
  `PrId` int(11) NOT NULL DEFAULT 0,
  `pr_service_default` enum('false','true') NOT NULL

    `pl_pr_id` int(11) NOT NULL,
  `pl_location` text DEFAULT NULL


    `rids_timestamp` datetime DEFAULT NULL,
  `rids_image_uuid` varchar(50) DEFAULT NULL,
  `rids_as_id` int(11) DEFAULT NULL


  `ris_id` int(11) NOT NULL AUTO_INCREMENT,
  `ris_timestamp` datetime DEFAULT NULL,
  `ris_link` varchar(255) DEFAULT NULL,
  `ris_imagelink` varchar(11) DEFAULT NULL,
  `ris_as_id` int(11) DEFAULT NULL,


  `ss_id` int(11) NOT NULL AUTO_INCREMENT,
  `ss_timestamp` datetime DEFAULT NULL,
  `ss_keywords` varchar(255) DEFAULT NULL,
  `ss_found` int(11) DEFAULT NULL,
  `ss_ug_id` varchar(255) DEFAULT NULL,
  `ss_type` varchar(50) DEFAULT NULL,
  `ss_country` varchar(255) DEFAULT NULL,

    `sfo_parent_uuid` varchar(64) DEFAULT NULL,
  `sfo_uuid` varchar(64) NOT NULL,
  `sfo_value` varchar(128) NOT NULL,

    `scm_ca_id` int(11) DEFAULT NULL,
  `scm_lg_id` int(11) DEFAULT NULL,
  `scm_ca_active` int(11) DEFAULT NULL

   `sts_id` int(11) NOT NULL DEFAULT 0,
  `StName` varchar(127) DEFAULT NULL,
  `StCountryLink` int(11) DEFAULT NULL,
  `StCode` varchar(50) DEFAULT NULL,

  `sts_id` bigint(11) NOT NULL AUTO_INCREMENT,
  `sts_as_id` int(11) DEFAULT NULL,
  `sts_access_timestamp` datetime DEFAULT NULL,
  `sts_referrer` varchar(255) DEFAULT NULL,
  `sts_client_id` varchar(32) DEFAULT NULL,
  `sts_client_browser` varchar(50) DEFAULT NULL,
  `sts_country` varchar(255) DEFAULT NULL,


  `te_id` int(11) NOT NULL DEFAULT 0,
  `te_customer` varchar(255) DEFAULT NULL,
  `te_text` longtext DEFAULT NULL,
  `te_date` date DEFAULT NULL,
  `te_as_id` int(11) DEFAULT NULL,


    `tr_id` int(11) NOT NULL AUTO_INCREMENT,
  `tr_reference` varchar(127) DEFAULT NULL,
  `tr_timestamp` datetime DEFAULT NULL,
  `tr_processed_date_time` datetime DEFAULT NULL,
  `tr_total` double(16,4) DEFAULT NULL,
  `tr_charge_total` varchar(127) DEFAULT NULL,
  `tr_nzd_total_charged` double DEFAULT NULL,
  `tr_currency_link` int(11) DEFAULT NULL,
  `tr_currency_code` varchar(5) DEFAULT NULL,
  `tr_currency_symbol` varchar(5) DEFAULT NULL,
  `tr_payment_details_szln` longtext DEFAULT NULL,
  `tr_status_link` int(11) DEFAULT 1,
  `tr_client_name` varchar(255) DEFAULT NULL,
  `tr_client_email` varchar(255) DEFAULT NULL,
  `tr_payment_method` varchar(127) DEFAULT NULL,
  `tr_token` varchar(127) DEFAULT NULL,
  `tr_completed` tinyint(1) NOT NULL DEFAULT 0,
  `tr_sent_information` longtext DEFAULT NULL,
  `tr_result` longtext DEFAULT NULL,
  `tr_fraud_score` float DEFAULT NULL,
  `tr_fraud` enum('','Blacklist','Maxmind','BadCustomer') DEFAULT NULL,
  `tr_ip_address` varchar(15) DEFAULT NULL,
  `tr_browser_ident` text DEFAULT NULL,
  `tr_fingerprint` text DEFAULT NULL,
  `tr_incl_shipping` double(16,3) DEFAULT NULL,
  `tr_excl_shipping` double(16,3) DEFAULT NULL,
  `tr_profit` double(16,3) DEFAULT NULL,
  `tr_used_credit` double(16,3) NOT NULL DEFAULT 0.000,
  `tr_reship_link` int(11) DEFAULT NULL,
  `tr_language` int(11) NOT NULL DEFAULT 0,
  `tr_vendors` varchar(64) DEFAULT NULL,
  `tr_exchange_rate_index` int(11) DEFAULT NULL,
  `tr_bank` int(11) NOT NULL DEFAULT 0,
  `tr_order_total` double(16,3) DEFAULT NULL,
  `tr_box_cost` double(16,3) DEFAULT NULL,
  `tr_processor_cost` double(16,3) DEFAULT NULL,
  `tr_session` varchar(64) DEFAULT NULL,
  `tr_gateway_option` int(11) DEFAULT NULL,
  `tr_payment_attempts` int(11) NOT NULL DEFAULT 0,
  `tr_browser_language` varchar(255) DEFAULT NULL,
  `tr_usd_rate` double(16,4) NOT NULL DEFAULT 1.0000,


  `ug_id` int(11) NOT NULL DEFAULT 0,
  `ug_name` varchar(50) DEFAULT NULL,
  `ug_mailing_list` tinyint(1) DEFAULT NULL,
  `ug_uuid` varchar(40) DEFAULT NULL,
  `ug_reviewer` tinyint(1) DEFAULT NULL,

    `pag_id` int(11) NOT NULL DEFAULT 0,
  `pag_us_id` int(11) DEFAULT NULL,
  `pag_content` longtext DEFAULT NULL,
  `pag_as_id` int(11) DEFAULT NULL,

    `us_id` int(11) NOT NULL DEFAULT 0,
  `us_first_name` varchar(127) DEFAULT NULL,
  `us_last_name` varchar(127) DEFAULT NULL,
  `us_email` varchar(128) DEFAULT NULL,
  `us_html_email` tinyint(1) DEFAULT 1,
  `us_user_name` varchar(128) DEFAULT NULL,
  `us_password` varchar(255) DEFAULT NULL,
  `us_activated` datetime DEFAULT NULL,
  `us_name` longtext DEFAULT NULL,
  `us_0_50A1` longtext DEFAULT NULL,
  `us_0_50A2` longtext DEFAULT NULL,
  `us_0_B4BF` longtext DEFAULT NULL,
  `us_0_B4C0` longtext DEFAULT NULL,
  `us_0_B4C1` longtext DEFAULT NULL,
  `us_0_50A4` longtext DEFAULT NULL,
  `us_no_spam` tinyint(1) DEFAULT NULL,
  `us_referral_user_name` varchar(255) DEFAULT NULL,
  `us_email_state` char(1) DEFAULT NULL,
  `us_email_next` date DEFAULT NULL,
  `us_pinyin_name` varchar(255) DEFAULT NULL,
  `us_pinyin_address` varchar(255) DEFAULT NULL,
  `us_wholesaler` char(1) DEFAULT NULL,
  `us_login_url` varchar(200) DEFAULT NULL,
  `us_chinese_id` int(11) DEFAULT NULL,
  `us_token` varchar(40) DEFAULT NULL,
  `us_confirm_receipt` tinyint(1) DEFAULT NULL,
  `us_login_note` text DEFAULT NULL,
  `us_notes` text DEFAULT NULL,
  `us_permanent_tracking` tinyint(1) DEFAULT 0,
  `us_temporary_tracking` int(11) NOT NULL DEFAULT 0,
  `us_discount` int(11) NOT NULL DEFAULT 0,
  `us_discount_expires` timestamp NOT NULL DEFAULT '2010-01-01 05:00:00',
  `us_payment_gateway` int(11) DEFAULT NULL,
  `us_account_credit` float NOT NULL DEFAULT 0,
  `us_admin_level` int(11) DEFAULT NULL,
  `us_members_viewed` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `us_shipping_label` longtext DEFAULT NULL,
  `us_credit_from_gateway_option` int(11) DEFAULT NULL,
  `us_no_chargeback_count` int(11) NOT NULL DEFAULT 0,
  `us_do_not_track` enum('false','true') NOT NULL DEFAULT 'false',
  `us_bl_id` int(11) DEFAULT NULL,
  `us_do_not_address_check` enum('false','true') NOT NULL DEFAULT 'false',
  `us_credit_notes` text DEFAULT NULL,
  `us_has_import_license` enum('false','true') NOT NULL DEFAULT 'false',
  `us_country_distributor` int(11) DEFAULT NULL,
  `us_vendor_distributor` int(11) DEFAULT NULL,


  `wpc_id` int(11) NOT NULL DEFAULT 0,
  `wpc_default_currency_details` longtext DEFAULT NULL,
  `wpc_use_cheque` tinyint(1) DEFAULT NULL,
  `wpc_use_credit_card` tinyint(1) DEFAULT NULL,
  `wpc_cheque_details` longtext DEFAULT NULL,
  `wpc_card_details` longtext DEFAULT NULL,
  `wpc_secure_server` varchar(255) DEFAULT NULL,
  `wpc_direct_payment` tinyint(1) DEFAULT NULL,
  `wpc_direct_payment_details` longtext DEFAULT NULL,
  `wpc_can_invoice` tinyint(1) DEFAULT NULL,
  `wpc_invoice_details` longtext DEFAULT NULL,
  `wpc_use_collection` tinyint(1) DEFAULT NULL,
  `wpc_collection_details` longtext DEFAULT NULL,


