csub \*.html OnlineShop_BlackList shopsystem_blacklist
csub \*.html OnlineShop_Categories shopsystem_categories
csub \*.html OnlineShop_CategoryDescriptions shopsystem_category_descriptions
csub \*.html OnlineShop_ComboProducts shopsystem_combo_products
csub \*.html OnlineShop_DiscountCodes shopsystem_discount_codes
csub \*.html OnlineShop_DiscountGroups  shopsystem_discount_groups
csub \*.html OnlineShop_ExternalOrderSheets shopsystem_order_sheets
csub \*.html OnlineShop_ExternalOrderSheetsItems shopsystem_order_sheets_items
csub \*.html OnlineShop_ExternalOrders shopsystem_order_items
csub \*.html OnlineShop_FeaturesAdministration shopsystem_features_administration
csub \*.html OnlineShop_Invoices shopsystem_invoices
csub \*.html OnlineShop_OrderNotes shopsystem_order_notes
csub \*.html OnlineShop_OrderProducts shopsystem_order_products
csub \*.html OnlineShop_Orders shopsystem_orders
csub \*.html OnlineShop_ProductCustomerRatings shopsystem_product_customer_ratings
csub \*.html OnlineShop_ProductDescriptions shopsystem_product_descriptions
csub \*.html OnlineShop_ProductExtendedOptions shopsystem_product_extended_options
csub \*.html OnlineShop_Products shopsystem_products
csub \*.html OnlineShop_QuickOrderCategories shopsystem_quick_categories
csub \*.html OnlineShop_Refunds shopsystem_refunds
csub \*.html OnlineShop_ServiceCompany shopsystem_service_company
csub \*.html OnlineShop_ServiceInvoice shopsystem_service_invoice
csub \*.html OnlineShop_ShippedProducts shopsystem_shipped_products
csub \*.html OnlineShop_ShippingCharges shopsystem_shipping_charges
csub \*.html OnlineShop_Statistics shopsystem_statistics
csub \*.html OnlineShop_StockNotifications shopsystem_stock_notifications
csub \*.html OnlineShop_StockOrders shopsystem_stock_orders
csub \*.html OnlineShop_SupplierOrderSheets shopsystem_supplier_order_sheets
csub \*.html OnlineShop_SupplierOrderSheetsItems shopsystem_supplier_order_sheets_items
csub \*.html OnlineShop_TaxCodes shopsystem_tax_codes
csub \*.html OnlineShop_TaxRates shopsystem_tax_rates
csub \*.html OnlineShop_TaxZoneCountries shopsystem_tax_zone_countries
csub \*.html OnlineShop_TaxZones shopsystem_tax_zones
csub \*.html OnlineShop_TransitDocGroup shopsystem_transit_document_group
csub \*.html OnlineShop_TransitDocGroupLink shopsystem_transit_document_group_link
csub \*.html OnlineShop_TransitDocs shopsystem_transit_documents
csub \*.html OnlineShop_UserPoints shopsystem_user_points
